# Generated by Django 3.1.5 on 2021-02-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_auto_20210209_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
