# Generated by Django 3.1.5 on 2021-02-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='hiiiiii', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
