# Generated by Django 3.1.5 on 2021-02-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_auto_20210210_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='hiiiiii', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
