# Generated by Django 3.1.5 on 2021-02-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_auto_20210210_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='is_public',
        ),
    ]
