# Generated by Django 3.1.5 on 2021-02-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_auto_20210210_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post1',
        ),
    ]
