# Generated by Django 3.1.5 on 2021-02-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0009_auto_20210211_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='is_public',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
