# Generated by Django 3.1.5 on 2021-02-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0012_auto_20210211_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='is_public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
