# Generated by Django 3.1.5 on 2021-02-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0014_auto_20210211_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='image',
        ),
        migrations.AddField(
            model_name='post1',
            name='image1',
            field=models.ImageField(default='blogsite/static/images/Cap_comformation_skn.jpg', upload_to='blogsite/static/images'),
        ),
    ]
